server:
  port: 8086
spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.3.102
    virtual-host: /cloud
    username: cloud
    password: cloud
  redis:
    port: 6379
    host: 192.168.3.102
    database: 0

  datasource:
    url: jdbc:mysql://192.168.3.102:3306/cloud
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

mybatis:
  type-aliases-package: com.cloud.user.pojo
